-- Dieser Schritt wird durch 01-analytics.sh abgedeckt, das die Passwörter
-- aus den Umgebungsvariablen CUBE_RW_PASSWORD / CUBE_RO_PASSWORD liest.
-- Datei bleibt als Platzhalter erhalten (leere SQL-Datei ist gültig).
